import Head from "next/head";

const Wrapper = ({ children }) => {
  return (
    <div className="font-Inter">
      <Head>
        <title>DCX.DO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="logo" href="/logo.svg" />
      </Head>
      <div>{children}</div>
    </div>
  );
};

export default Wrapper;
